``` mermaid

flowchart LR
  %% Kolommen: Bronhouders <--> Generieke bronontsluiting <--> Stroomspecifieke voorziening <--> Afnemer
  bron[("Overheidsbronnen<br/>BRP · BD · UWV · KvK…")]:::bron

    subgraph gbo["GBO Basis"]
        direction TB
        fsc_pap("PAP<br />(beleidsregels)"):::gbo
        fsc("FSC / GraphQL / PBAC<br/>(generieke bronontsluiting)"):::gbo
        fsc_tools("GBO tools<br />(vertaallaag)"):::gbo
        fsc_pap <--> fsc
        fsc <--> fsc_tools
    end

    bron <--> gbo

    subgraph eudi["EUDI-Wallet"]
      direction LR
      eudi_asi("ASI-provider<br/>(verify dienst)"):::gbo
      eudi_pubeaa("PubEAA-provider<br/>(PubEAA)"):::gbo
      eudi_qeaa["QTSP<br/>(QEAA)"]:::eudi
      eudi_wallet["EUDI-Wallet burger"]:::eudi
      eudi_asi <--> eudi_qeaa <--> eudi_wallet
    end
    gbo <--> eudi_asi
    gbo <--> eudi_pubeaa <--> eudi_wallet

    subgraph oots["SDG / OOTS"]
      direction LR
      oots_adapter("OOTS adapter<br />(semantische mapping)"):::gbo
      oots_basis["Basisinrichting OOTS<br/>RINIS / BZK"]:::oots
      oots_afnemer["Europese overheid<br/>SDG-portaal"]:::oots
    end
    gbo <--> oots_adapter <--> oots_basis <--> oots_afnemer

    subgraph dvtp["DvTP"]
      direction LR
      dvtp_toestemming("Toestemmingsvoorziening"):::gbo
      dvtp_pseudoniem["Pseudonimiseervoorziening<br/>(BSNk PP)"]:::dvtp
      dvtp_afnemer["Private dienstverlener"]:::dvtp

    end
    gbo <--> dvtp_toestemming <--> dvtp_pseudoniem <--> dvtp_afnemer

    burger["Burger"]:::burger
    eudi_wallet <--> burger
    oots_afnemer <--> burger
    dvtp_afnemer <--> burger

  classDef bron fill:#edf7df,stroke:#6aa13a,color:#27500a
  classDef generiek fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef eudi fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef oots fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef dvtp fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef gbo fill:#fff0e8,stroke:#185fa5,color:#0c447c
  classDef burger fill:#edf7df,stroke:#6aa13a,color:#27500a

```
